### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by ur0n2** [ur0n2/dotfiles-for-windows#38]
- [ ] 휴지통 대화 상자 X 옵션 설정
- [ ] 폴더 옵션 설정
- [x] 접근성센터 옵션 -> win+방향키가 안먹음.. for mstsc... 불편 PASS
- [ ] python27 환경변수 추가
- [ ] 파일 보호 해제 모듈 따로 repo 생성
- [x] ~~utorrent 설정-> ini가 아님, encode 되어있음 PASS~~
- [x] psi 테마설정 #37 
- [x] 순서변경: 내 깃헛에서 자료 다운-> 테마cmd라이브러리 ps1실행 -> linked복사 -> 파일보호해제 
- [x] setup.ps1 리팩토링
- [x] add "test windows os" on readme.md .
- [x] 한줄설치
- [x] readme.md finish off. 
- [x] 1.0 release.
- [ ] Test Case 추가(특히 파일보호 Verification부분 최우선)
- [ ] ci/cd
